//
//  DeveloperPreview.swift
//  UniParkV2
//
//  Created by Tomas Angel on 24/10/24.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Edificio SD Universidad de los Andes",
            ownerImageUrl: "unandes-logo",
            numberOfSpots: 30,
            pricePlain: 16000,
            pricePerMinute: 300,
            latitude: 4.6042,
            longitude: 74.0659,
            address: "Calle 21 #1-2 a 1-58",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Edificio SD",
            rating: 4.9,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.superHost],
            amenities: [.tv, .sinLlaves],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "87654321",
            ownerName: "Tequendama Uniandes",
            ownerImageUrl: "tequendama-image",
            numberOfSpots: 20,
            pricePlain: 15000,
            pricePerMinute: 100,
            latitude: 4.603918756811246,
            longitude: -74.06553872762684,
            address: "Cra 1 #22-37, Bogotá",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Parqueadero Tequendama Uniandes",
            rating: 4.5,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.superHost],
            amenities: [.sinLlaves],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "44332211",
            ownerName: "La Mutual",
            ownerImageUrl: "mutual-image",
            numberOfSpots: 30,
            pricePlain: 12000,
            pricePerMinute: 77,
            latitude: 4.6040486188222625,
            longitude: -74.06678321165559,
            address: "Cl. 20 #2 - 26, Bogotá",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Parqueadero La Mutual",
            rating: 4.2,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.superHost],
            amenities: [.sinLlaves],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "55443322",
            ownerName: "City U",
            ownerImageUrl: "city-u-image",
            numberOfSpots: 50,
            pricePlain: 20000,
            pricePerMinute: 110,
            latitude: 4.603264909381853,
            longitude: -74.06720426873294,
            address: "Ac. 19 #2a - 10, Bogotá",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Parqueadero City U",
            rating: 3.5,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.selfCheckIn],
            amenities: [.tv],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "66554433",
            ownerName: "Monserrate",
            ownerImageUrl: "monserrate-image",
            numberOfSpots: 35,
            pricePlain: 12000,
            pricePerMinute: 80,
            latitude: 4.604939736852341,
            longitude: -74.06522445714218,
            address: "Cra. 1 #22-37, Bogotá",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Parqueadero Monserrate",
            rating: 2.5,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.superHost],
            amenities: [.sinLlaves],
            type: .house
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "77665544",
            ownerName: "Público W.F.S",
            ownerImageUrl: "publico-wfs-image",
            numberOfSpots: 20,
            pricePlain: 14000,
            pricePerMinute: 75,
            latitude: 4.60364652371214,
            longitude: -74.06500945369261,
            address: "Dg. 20A #1-20, Bogotá",
            city: "Bogotá",
            university: "Universidad de los Andes",
            title: "Parqueadero público W.F.S",
            rating: 1.9,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.selfCheckIn, .superHost],
            amenities: [.sinLlaves],
            type: .apartment
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: "88776655",
            ownerName: "La Tadeo",
            ownerImageUrl: "la-tadeo-image",
            numberOfSpots: 20,
            pricePlain: 14000,
            pricePerMinute: 80,
            latitude: 4.605855878988005,
            longitude: -74.06726570815394,
            address: "Cl 22 #3-27, Bogotá",
            city: "Bogotá",
            university: "Universidad de la Tadeo",
            title: "Parqueadero la Tadeo",
            rating: 4.9,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            features: [.superHost],
            amenities: [.tv, .sinLlaves],
            type: .house
        )
    ]
}
